### ISSUE TITLE
Segmentation Fault in hyriseBenchmarkJoinOrder

### ISSUE THREAD

**Issue by engelfa** [hyrise/hyrise#1724]
```Thread 1 "hyriseBenchmark" received signal SIGSEGV, Segmentation fault.
__memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
383	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __memmove_sse2_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:383
#1  0x0000555557fcfdc5 in std::__copy_move<true, true, std::random_access_iterator_tag>::__copy_m<int> (__first=0x4, __last=0x0, __result=0x0)
    at /usr/include/c++/8/bits/stl_algobase.h:368
#2  0x0000555557fc689e in std::__copy_move_a<true, int*, int*> (__first=0x4, __last=0x0, __result=0x0) at /usr/include/c++/8/bits/stl_algobase.h:386
#3  0x0000555557fbb7d0 in std::__copy_move_a2<true, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > > (__first=<Fehler beim Lesen der Variable: Cannot access memory at address 0x4>, 
    __last=non-dereferenceable iterator for std::vector, __result=non-dereferenceable iterator for std::vector) at /usr/include/c++/8/bits/stl_algobase.h:422
#4  0x0000555557fb0d42 in std::move<__gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > >, __gnu_cxx::__normal_iterator<int*, std::vector<int, std::allocator<int> > > > (__first=<Fehler beim Lesen der Variable: Cannot access memory at address 0x4>, __last=non-dereferenceable iterator for std::vector, 
    __result=non-dereferenceable iterator for std::vector) at /usr/include/c++/8/bits/stl_algobase.h:487
#5  0x00005555582b58a1 in std::vector<int, std::allocator<int> >::_M_erase (this=0x7fffffffb3c0, __position=non-dereferenceable iterator for std::vector)
    at /usr/include/c++/8/bits/vector.tcc:163
#6  0x00005555582b2c55 in std::vector<int, std::allocator<int> >::erase (this=0x7fffffffb3c0, __position=non-dereferenceable iterator for std::vector)
    at /usr/include/c++/8/bits/stl_vector.h:1318
#7  0x000055555829cf11 in opossum::AbstractHistogram<int>::split_at_bin_bounds (this=0x7ffff71296b0, additional_bin_edges=std::vector of length 0, capacity 0)
    at /home/Fabian.Engel/hyrise/src/lib/statistics/statistics_objects/abstract_histogram.cpp:681
#8  0x000055555828472b in opossum::CardinalityEstimator::<lambda(auto:19)>::operator()<boost::hana::basic_type<int> >(boost::hana::basic_type<int>) const (
    __closure=0x7fffffffb9e0, data_type_t=...) at /home/Fabian.Engel/hyrise/src/lib/statistics/cardinality_estimator.cpp:518```

**Comment by engelfa** [comment]
Fixed in #1678
