### ISSUE TITLE
Join-Order Query 16a segfaults

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#1899]
```
[master]> ./build-release/hyriseBenchmarkJoinOrder -t 1
[...]
- Benchmarking 16a
Segmentation fault
```

```
(gdb) bt
#0  0x0000000002f25b7c in opossum::RangeFilter<int>::does_not_contain(opossum::PredicateCondition, boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> const&, std::optional<boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> > const&) const (this=0x7ffff703fb10,
    predicate_condition=opossum::PredicateCondition::LessThanEquals, variant_value=...,
    variant_value2=std::optional<boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5>, int, boost::mpl::l_item<mpl_::long_<4>, long, boost::mpl::l_item<mpl_::long_<3>, float, boost::mpl::l_item<mpl_::long_<2>, double, boost::mpl::l_item<mpl_::long_<1>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >>> [no contained value])
    at ../src/lib/statistics/statistics_objects/range_filter.cpp:223
#1  0x0000000002f25ea2 in opossum::RangeFilter<int>::does_not_contain(opossum::PredicateCondition, boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> const&, std::optional<boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> > const&) const (this=0x7ffff703fb10,
    predicate_condition=opossum::PredicateCondition::BetweenUpperExclusive, variant_value=...,
    variant_value2=std::optional<boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5>, int, boost::mpl::l_item<mpl_::long_<4>, long, boost::mpl::l_item<mpl_::long_<3>, float, boost::mpl::l_item<mpl_::long_<2>, double, boost::mpl::l_item<mpl_::long_<1>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >>> = {...})
    at ../src/lib/statistics/statistics_objects/range_filter.cpp:255
#2  0x0000000002e27c87 in opossum::ChunkPruningRule::_can_prune(opossum::BaseAttributeStatistics const&, opossum::PredicateCondition, boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> const&, std::optional<boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> > const&)::$_1::operator()<boost::hana::basic_type<int> >(boost::hana::basic_type<int>) const (this=0x7ffed35f80b0, data_type_t=...)
    at ../src/lib/optimizer/strategy/chunk_pruning_rule.cpp:183
```

```
(gdb) f 0
#0  0x0000000002f25b7c in opossum::RangeFilter<int>::does_not_contain(opossum::PredicateCondition, boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> const&, std::optional<boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6l>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5l>, int, boost::mpl::l_item<mpl_::long_<4l>, long, boost::mpl::l_item<mpl_::long_<3l>, float, boost::mpl::l_item<mpl_::long_<2l>, double, boost::mpl::l_item<mpl_::long_<1l>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >> > const&) const (this=0x7ffff703fb10,
    predicate_condition=opossum::PredicateCondition::LessThanEquals, variant_value=...,
    variant_value2=std::optional<boost::variant<boost::detail::variant::over_sequence<boost::mpl::l_item<mpl_::long_<6>, opossum::NullValue, boost::mpl::l_item<mpl_::long_<5>, int, boost::mpl::l_item<mpl_::long_<4>, long, boost::mpl::l_item<mpl_::long_<3>, float, boost::mpl::l_item<mpl_::long_<2>, double, boost::mpl::l_item<mpl_::long_<1>, std::__cxx11::basic_string<char, std::char_traits<char>, boost::container::pmr::polymorphic_allocator<char> >, boost::mpl::l_end> > > > > > >>> [no contained value])
    at ../src/lib/statistics/statistics_objects/range_filter.cpp:223
223	      return value < min;
(gdb) p value
$3 = 100
(gdb) p min
$4 = (const int &) <error reading variable>
(gdb) p ranges
$5 = std::vector of length 0, capacity 0
```

**Comment by mrks** [comment]
Once this is fixed, let the mini-JOB run as part of CI:

```diff
diff --git a/scripts/test/hyriseBenchmarkJoinOrder_test.py b/scripts/test/hyriseBenchmarkJoinOrder_test.py
index 020da5f5..04b5398f 100755
--- a/scripts/test/hyriseBenchmarkJoinOrder_test.py
+++ b/scripts/test/hyriseBenchmarkJoinOrder_test.py
@@ -75,7 +75,6 @@ def main():

   arguments = {}
   arguments["--table_path"] = "'resources/test_data/imdb_sample/'"
-  arguments["--queries"] = "'3b'"
   arguments["--time"] = "10"
   arguments["--runs"] = "100"
   arguments["--warmup"] = "10"
@@ -101,7 +100,6 @@ def main():
   benchmark.expect("Not caching tables as binary files")
   benchmark.expect("Benchmarking queries from third_party/join-order-benchmark")
   benchmark.expect("Running on tables from resources/test_data/imdb_sample/")
-  benchmark.expect("Running subset of queries: 3b")
   benchmark.expect("Multi-threaded Topology:")

   close_benchmark(benchmark)
```
