### ISSUE TITLE
CI crashes on compareBenchmarkScriptTest.py

### ISSUE THREAD

**Issue by julianmenzler** [hyrise/hyrise#2196]
I experienced the CI crashing because of `compareBenchmarkScriptTest.py`.
This must be related to the changes introduced by #2091.

Looks like a bug @Bouncner?

Here is the CI's output:

```
...
- Results for Delivery
  -> Executed 1 times
- Results for New-Order
  -> Executed 18 times
- Results for Order-Status
  -> Executed 0 times
- Results for Payment
  -> Executed 20 times
- Results for Stock-Level
  -> Executed 4 times
/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3621: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3372: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "./scripts/test/hyriseBenchmarkTPCC_test.py", line 77, in <module>
    main()
  File "./scripts/test/hyriseBenchmarkTPCC_test.py", line 73, in main
    CompareBenchmarkScriptTest(compare_benchmarks_path, output_filename_1, output_filename_2).run()
  File "/home/jenkins/workspace/hyrise_hyrise_PR-2193@2/scripts/test/compareBenchmarkScriptTest.py", line 41, in run
    self.check_result_table()
  File "/home/jenkins/workspace/hyrise_hyrise_PR-2193@2/scripts/test/compareBenchmarkScriptTest.py", line 101, in check_result_table
    assert_latency_equals(
  File "/home/jenkins/workspace/hyrise_hyrise_PR-2193@2/scripts/test/compareBenchmarkScriptTest.py", line 13, in assert_latency_equals
    avg_latency = sum(runtimes) / item_count / 1_000_000
ZeroDivisionError: division by zero
script returned exit code 1
```

**Comment by Bouncner** [comment]
Will take a look. Who the hell implemented that?
