### ISSUE TITLE
hyriseServerTest is not properly isolated

### ISSUE THREAD

**Issue by mrks** [hyrise/hyrise#2320]
https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/master/214/pipeline
https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/master/213/pipeline

We should make sure that the ports opened in the Docker containers do not conflict.

**Comment by Bouncner** [comment]
Can we avoid exposing them at all?

**Comment by mrks** [comment]
Would have to look into the Docker network settings for that. An easy fix would be to simply use `-p 0` and parse the used port from the output.

**Comment by mrks** [comment]
Same for hyriseServer_test.py:

```
+ ./scripts/test/hyriseServer_test.py gcc-release

Traceback (most recent call last):

  File "./scripts/test/hyriseServer_test.py", line 33, in <module>

    main()

  File "./scripts/test/hyriseServer_test.py", line 18, in main

    benchmark.expect_exact("Server started at 0.0.0.0 and port 5432", timeout=120)

  File "/usr/local/lib/python3.8/dist-packages/pexpect/spawnbase.py", line 421, in expect_exact

    return exp.expect_loop(timeout)

  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 179, in expect_loop

    return self.eof(e)

  File "/usr/local/lib/python3.8/dist-packages/pexpect/expect.py", line 122, in eof

    raise exc

pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

<pexpect.pty_spawn.spawn object at 0x7f301d080c40>

command: gcc-release/hyriseServer

args: ['gcc-release/hyriseServer', '--benchmark_data=tpc-h:0.01']

buffer (last 100 chars): b''

before (last 100 chars): b"tance of 'boost::wrapexcept<boost::system::system_error>'\r\n  what():  bind: Address already in use\r\n"

after: <class 'pexpect.exceptions.EOF'>

match: None

match_index: None

exitstatus: None

flag_eof: True

pid: 30848

child_fd: 5

closed: False

timeout: 10

delimiter: <class 'pexpect.exceptions.EOF'>

logfile: None

logfile_read: None

logfile_send: None

maxread: 2000

ignorecase: False

searchwindowsize: None

delaybeforesend: 0.05

delayafterclose: 0.1

delayafterterminate: 0.1

searcher: searcher_string:

    0: b'Server started at 0.0.0.0 and port 5432'

script returned exit code 1
``

**Comment by Bouncner** [comment]
Just to be sure I get you right: that's the same error, right? The `Same for hyriseServer_test.py:` confuses me.

**Comment by mrks** [comment]
Ah, right. I was confused because of the issue's title. Will change it.
