### ISSUE TITLE
ODR Violations with Plugins

### ISSUE THREAD

**Issue by Bouncner** [hyrise/hyrise#2632]
When we load plugins, we are violating the one definition rule (ODR) as both libHyrise as well as the plugin use libBenchmark.

```
[----------] 14 tests from PluginManagerTest
[ RUN      ] PluginManagerTest.LoadUnloadPlugin
=================================================================
==532123==ERROR: AddressSanitizer: odr-violation (0x7f5a2ccb0cc0):
  [1] size=39 'typeinfo name for hyrise::AbstractBenchmarkItemRunner' /var/lib/jenkins/workspace/hyrise_hyrise_PR-2611/src/benchmarklib/abstract_benchmark_item_runner.cpp
  [2] size=39 'typeinfo name for hyrise::AbstractBenchmarkItemRunner' /var/lib/jenkins/workspace/hyrise_hyrise_PR-2611/src/benchmarklib/abstract_benchmark_item_runner.cpp
These globals were registered at these points:
  [1]:
    #0 0x563995775956 in __asan_register_globals (/var/lib/jenkins/workspace/hyrise_hyrise_PR-2611/clang-debug-addr-ub-leak-sanitizers/hyriseTest+0x7f39956) (BuildId: 87a269d6b182aa9a)
    #1 0x563995776a7d in __asan_register_elf_globals (/var/lib/jenkins/workspace/hyrise_hyrise_PR-2611/clang-debug-addr-ub-leak-sanitizers/hyriseTest+0x7f3aa7d) (BuildId: 87a269d6b182aa9a)
    #2 0x7f5a503cd36d in call_init elf/dl-init.c:90:3

  [2]:
    #0 0x563995775956 in __asan_register_globals (/var/lib/jenkins/workspace/hyrise_hyrise_PR-2611/clang-debug-addr-ub-leak-sanitizers/hyriseTest+0x7f39956) (BuildId: 87a269d6b182aa9a)
    #1 0x563995776a7d in __asan_register_elf_globals (/var/lib/jenkins/workspace/hyrise_hyrise_PR-2611/clang-debug-addr-ub-leak-sanitizers/hyriseTest+0x7f3aa7d) (BuildId: 87a269d6b182aa9a)
    #2 0x7f5a503cd36d in call_init elf/dl-init.c:90:3

==532123==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'typeinfo name for hyrise::AbstractBenchmarkItemRunner' at /var/lib/jenkins/workspace/hyrise_hyrise_PR-2611/src/benchmarklib/abstract_benchmark_item_runner.cpp
==532123==ABORTING
script returned exit code 1
```

**Comment by dey4ss** [comment]
As plugins can in theory include anything from the other components, are there any chances we can avoid that? Guess forward decl does not help as linking the shared libraries is probably the problem
